### ISSUE TITLE
Why ssh is used in Switch.__init__ even if connection_type="https"?

### ISSUE THREAD

**Issue by 212850a** [Cisco-SAN/mdssdk#15]
Hi I was trying to test mdssdk.Switch as from examples with connection_type="https", but it looks like it still does ssh.
Why there is self._connect_via_ssh() in Switch.__init__?

**Comment by srbharadwaj** [comment]
That is correct by default we take a 'ssh' connection. This is because 
a) some switch types like n9k or FI doesn't support https/nxapi
b) MDS switches with version < 8.4(2) doesnt have NXAPI support for most commands

To accommodate these we always take a 'ssh' connection, depending on the type of switch or version we either use the ssh channel to send commands or nxapi(https) channel to send commands
